const {createClient}=window.supabase;const client=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const form=document.getElementById("registrationForm"), wrap=document.getElementById("formWrap"), success=document.getElementById("successState"), errorBox=document.getElementById("formError"), btn=document.getElementById("submitButton"), text=document.getElementById("buttonText"), spinner=document.getElementById("spinner"), about=document.getElementById("about"), count=document.getElementById("count");
document.getElementById("availableDate").min=new Date().toISOString().split("T")[0]; about.addEventListener("input",()=>count.textContent=about.value.length);
function err(id,msg){const el=document.getElementById(id),e=document.getElementById(id+"Error");if(el)el.classList.toggle("invalid",!!msg);if(e)e.textContent=msg||""}
function clear(){["name","email","year","domain","skills","experience","availableDate"].forEach(x=>err(x,""));errorBox.classList.add("hidden")}
function validate(){clear();let ok=true;const name=document.getElementById("name").value.trim(),email=document.getElementById("email").value.trim(),year=document.getElementById("year").value,domain=document.querySelector('input[name="domain"]:checked'),skills=[...document.querySelectorAll('input[name="skills"]:checked')],exp=document.getElementById("experience").value,date=document.getElementById("availableDate").value,today=new Date().toISOString().split("T")[0];
if(name.length<2){err("name","Please enter your full name.");ok=false} if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){err("email","Enter a valid email.");ok=false} if(!year){err("year","Choose your year.");ok=false} if(!domain){err("domain","Select a domain.");ok=false} if(!skills.length){err("skills","Select at least one skill.");ok=false} if(exp.trim().length<3){err("experience","Please describe at least one skill or area of knowledge.");ok=false} if(!date){err("availableDate","Choose a date.");ok=false}else if(date<today){err("availableDate","Date cannot be in the past.");ok=false}
if(!ok){errorBox.textContent="A few details need your attention.";errorBox.classList.remove("hidden")}return ok}
form.addEventListener("submit",async e=>{e.preventDefault();if(!validate())return;btn.disabled=true;text.classList.add("hidden");spinner.classList.remove("hidden");
const data={name:document.getElementById("name").value.trim(),email:document.getElementById("email").value.trim().toLowerCase(),year:document.getElementById("year").value,domain:document.querySelector('input[name="domain"]:checked').value,skills:[...document.querySelectorAll('input[name="skills"]:checked')].map(x=>x.value),experience:document.getElementById("experience").value.trim(),available_date:document.getElementById("availableDate").value,about:about.value.trim()};
const {error}=await client.from("responses").insert([data]);btn.disabled=false;text.classList.remove("hidden");spinner.classList.add("hidden");if(error){console.error(error);errorBox.textContent="Could not submit. Check your Supabase configuration.";errorBox.classList.remove("hidden");return}wrap.classList.add("hidden");success.classList.remove("hidden")});
document.getElementById("anotherResponse").addEventListener("click",()=>{form.reset();count.textContent="0";clear();success.classList.add("hidden");wrap.classList.remove("hidden")});