-- Run this in Supabase Dashboard -> SQL Editor

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  year text not null,
  domain text not null,
  skills text[] not null,
  experience text not null check (char_length(trim(experience)) between 3 and 400),
  available_date date not null,
  about text,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security.
alter table public.responses enable row level security;

-- Public users can INSERT responses, but cannot SELECT them.
create policy "Allow public form submissions"
on public.responses
for insert
to anon
with check (
  char_length(trim(name)) >= 2
  and position('@' in email) > 1
  and cardinality(skills) >= 1
  and experience between 0 and 20
);

-- Optional: only create a SELECT policy if you deliberately want
-- anonymous users to view submitted responses.
-- Do NOT enable this for a private/admin response page.
